### ISSUE TITLE
Course Materials

### ISSUE THREAD

**Issue by spacefan** [gmtsar/2022-unavco-course-gmtsar#2]
Hi Eric!
I'd like to ask, will the 2022 course materials be shared?

**Comment by Xiaohua-Eric-Xu** [comment]
I think they are already shared through google drive and youtube. https://drive.google.com/drive/u/1/folders/19WaYKJCFaruPa6UjvGsAWVdVB-pDD265
https://www.youtube.com/watch?v=q5iv1d4FILE&ab_channel=UNAVCO%2CInc.
https://www.youtube.com/watch?v=8fCN7My1GEQ&ab_channel=UNAVCO%2CInc.

**Comment by spacefan** [comment]
Thanks for your share
