### ISSUE TITLE
Tiny bug in Compute the Interferogram section

### ISSUE THREAD

**Issue by SeismoFelix** [gmtsar/2022-unavco-course-gmtsar#3]
Hi, 

In the [gmtsar_rs2_demo.ipynb](https://github.com/gmtsar/Earthscope-GMTSAR-Shortcourse/blob/main/Jupyter/gmtsar_rs2_demo.ipynb) notebook, in the section **Compute Interferogram**, the instruction `intf_dir = {ref_id + "_" + rep_id}` should be written without the curly brackets ({) because the directory to create in the example is **2011134_2011230**, instead of **{2011134_2011230}**. 

Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
Just made a fix. Thanks!
