### ISSUE TITLE
unwrap_parallel.csh

### ISSUE THREAD

**Issue by nicolaslecorvec** [gmtsar/2022-unavco-course-gmtsar#4]
**Describe the problem you met**
when I run 'unwrap_parallel.csh' intflist 6 in my GMTSAR\project\asc\merge 

i get:
directories.: Command not found.
Working on line 6536 ...

I added my GMTSAR\project\asc\merge to my $PATH

and I created the function 'unwrap_intf.csh' in my 'GMTSAR\project\asc\merge '

![image](https://github.com/user-attachments/assets/a7680a43-5b6a-44f6-9ce7-ecbd34db14d3)

**Comment by nicolaslecorvec** [comment]
I just made a test to run "unwrap_intf.csh" from another folder and it seems I have the same "directories.: Command not found."

➜  project unwrap_intf.csh                                                                           [🐍 lewagon]
directories.: Command not found.
ln: failed to create symbolic link './landmask_ra.grd': File exists
grdmath [ERROR]: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name
grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name
Setting search radius to be 300 ...
Reading in original grid...
nearest_grid [ERROR]: Cannot find file phase_tmp.grd
nearest_grid [ERROR]: Cannot find file phase_tmp.grd
nearest_grid [ERROR]: File phase_tmp.grd not found
[Session nearest_grid (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grdfile phase_tmp.grd
mv: cannot stat 'tmp.grd': No such file or directory
grd2xyz [ERROR]: Cannot find file phase_tmp.grd
grd2xyz [ERROR]: Cannot find file phase_tmp.grd
grd2xyz [ERROR]: File phase_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grd2xyz [ERROR]: Cannot find file corr_tmp.grd
grd2xyz [ERROR]: Cannot find file corr_tmp.grd
grd2xyz [ERROR]: File corr_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
unwrapping phase with snaphu - higher threshold for faster unwrapping
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files

snaphu v2.0.4
32 parameters input from file snaphu.conf.brief (297 lines total)
not enough input arguments.  type snaphu -h for help
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
xyz2grd [ERROR]: Cannot find file unwrap.out
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
xyz2grd [ERROR]: Cannot find file conncomp.out
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
grdmath [ERROR]: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdimage [ERROR]: Cannot find file unwrap.grd
grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use dd:mm[:ss] for regions given in arc
     degrees, minutes [and seconds]. Use -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected
     coordinates, with <unit> selected from e|f|k|M|n|u. [e] Use [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time
     axes. Append +r if -R specifies the coordinates of the lower left and upper right corners of a rectangular area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and grid dimensions, where <code> is a 2-
     char combo from [T|M|B][L|C|R] (top/middle/bottom/left/center/right) and grid spacing must be specified via
     -I<dx>[/<dy>] (also see -r).
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Unwrapped phase map: unwrap.pdf

**Comment by nicolaslecorvec** [comment]
the "intflist" is created by using "ls /path/to/F1/intf_all > intflist"

**Comment by YizhanZHAO** [comment]
> I just made a test to run "unwrap_intf.csh" from another folder and it seems I have the same "directories.: Command not found."
> 
> ➜ project unwrap_intf.csh [🐍 lewagon] directories.: Command not found. ln: failed to create symbolic link './landmask_ra.grd': File exists grdmath [ERROR]: corr_patch.grd is not a number, operator or file name grdmath [ERROR]: corr_patch.grd is not a number, operator or file name grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name Setting search radius to be 300 ... Reading in original grid... nearest_grid [ERROR]: Cannot find file phase_tmp.grd nearest_grid [ERROR]: Cannot find file phase_tmp.grd nearest_grid [ERROR]: File phase_tmp.grd not found [Session nearest_grid (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16) cannot open grdfile phase_tmp.grd mv: cannot stat 'tmp.grd': No such file or directory grd2xyz [ERROR]: Cannot find file phase_tmp.grd grd2xyz [ERROR]: Cannot find file phase_tmp.grd grd2xyz [ERROR]: File phase_tmp.grd not found [Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16) grd2xyz [ERROR]: Cannot find file corr_tmp.grd grd2xyz [ERROR]: Cannot find file corr_tmp.grd grd2xyz [ERROR]: File corr_tmp.grd not found [Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16) unwrapping phase with snaphu - higher threshold for faster unwrapping grdinfo [ERROR]: Cannot find file phase_patch.grd grdinfo [ERROR]: Must specify one or more input files
> 
> snaphu v2.0.4 32 parameters input from file snaphu.conf.brief (297 lines total) not enough input arguments. type snaphu -h for help grdinfo [ERROR]: Cannot find file phase_patch.grd grdinfo [ERROR]: Must specify one or more input files grdinfo [ERROR]: Cannot find file phase_patch.grd grdinfo [ERROR]: Must specify one or more input files xyz2grd [ERROR]: Cannot find file unwrap.out xyz2grd [ERROR]: Must specify -R option xyz2grd [ERROR]: Option -I: Must specify positive increment(s) grdinfo [ERROR]: Cannot find file phase_patch.grd grdinfo [ERROR]: Must specify one or more input files grdinfo [ERROR]: Cannot find file phase_patch.grd grdinfo [ERROR]: Must specify one or more input files xyz2grd [ERROR]: Cannot find file conncomp.out xyz2grd [ERROR]: Must specify -R option xyz2grd [ERROR]: Option -I: Must specify positive increment(s) grdmath [ERROR]: tmp.grd is not a number, operator or file name mv: cannot stat 'tmp.grd': No such file or directory grdgradient [ERROR]: Cannot find file unwrap.grd grdinfo [ERROR]: Cannot find file unwrap.grd grdinfo [ERROR]: Must specify one or more input files makecpt [ERROR]: Option T: Must specify valid min[/max[/inc[|+n]]] option grdinfo [ERROR]: Cannot find file unwrap.grd grdinfo [ERROR]: Must specify one or more input files grdinfo [ERROR]: Cannot find file unwrap.grd grdinfo [ERROR]: Must specify one or more input files grdimage [ERROR]: Cannot find file unwrap.grd grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates! psscale [ERROR]: Option -R parsing failure. Correct syntax:
> 
> -R///[+r] Specify the min/max coordinates of your data region in user units. Use dd:mm[:ss] for regions given in arc degrees, minutes [and seconds]. Use -R///[+u] for regions given in projected coordinates, with selected from e|f|k|M|n|u. [e] Use [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time axes. Append +r if -R specifies the coordinates of the lower left and upper right corners of a rectangular area. Alternatively, use -R`` //<n_columns>/<n_rows> for origin and grid dimensions, where ` is a 2- char combo from [T|M|B][L|C|R] (top/middle/bottom/left/center/right) and grid spacing must be specified via -I[/] (also see -r). psscale [ERROR]: Offending option -Runwrap.grd psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option. Unwrapped phase map: unwrap.pdf` ``

**Comment by YizhanZHAO** [comment]
I also encountered this problem, have you solved it?

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe try adding ./ in front of unwarp_intf.csh in your unwrap_parallel.csh script, i.e., change 
```
 27 foreach line (`awk '{print $0}' $1`)
 28   echo "unwrap_intf.csh $line > log_$line.txt" >> unwrap.cmd
 29 end
```
to 
```
 27 foreach line (`awk '{print $0}' $1`)
 28   echo "./unwrap_intf.csh $line > log_$line.txt" >> unwrap.cmd
 29 end
```
